### ISSUE TITLE
View crashes when trying to inflate

### ISSUE THREAD

**Issue by kcochibili** [gildaswise/HorizontalCounter#5]
Cause: NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setTint(int)' on a null object reference

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setTint(int)' on a null object reference
--
at androidx.core.graphics.drawable.DrawableCompat.setTint(DrawableCompat.java:136)
at com.gildaswise.horizontalcounter.HorizontalCounter.setPlusButtonColor(HorizontalCounter.java:173)
at com.gildaswise.horizontalcounter.HorizontalCounter.setupPlusButton(HorizontalCounter.java:162)
at com.gildaswise.horizontalcounter.HorizontalCounter.setupButtons(HorizontalCounter.java:133)
at com.gildaswise.horizontalcounter.HorizontalCounter.setupViews(HorizontalCounter.java:128)
at com.gildaswise.horizontalcounter.HorizontalCounter.init(HorizontalCounter.java:121)
at com.gildaswise.horizontalcounter.HorizontalCounter.&lt;init&gt;(HorizontalCounter.java:71)

```
How do I resolve this issue?

**Comment by gildaswise** [comment]
Hey, it's been a while since I saw a similar issue, could you add your Java/Kotlin code and the XML portion? It also may be because this library isn't updated to AndroidX yet.
